### ISSUE TITLE
Tonic error in POKER-DVS notebook tutorial running on Google Colab

### ISSUE THREAD

**Issue by fzi-neuromorphic** [norse/notebooks#14]
When running the notebook "Training a classifier on the event-based POKER-DVS dataset" on Google Colab without any modifications, I get the following error in code cell 6 ( "tonic.utils.plot_event_grid(events, trainset.ordering)" ):

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-084ef67ecd1e> in <module>()
----> 1 tonic.utils.plot_event_grid(events, trainset.ordering)

/usr/local/lib/python3.7/dist-packages/tonic/utils.py in plot_event_grid(events, ordering, axis_array, plot_frame_number)
     28     events = np.array(events)
     29     transform = transforms.Compose(
---> 30         [transforms.ToVoxelGrid(num_time_bins=np.product(axis_array))]
     31     )
     32     x_index = ordering.find("x")

TypeError: __init__() got an unexpected keyword argument 'num_time_bins'

![grafik](https://user-images.githubusercontent.com/87014751/126511800-01b1c626-d1a4-4c5a-bdbf-5eacb18a6a96.png)

**Comment by cpehle** [comment]
I think the tonic API might still be in flux. @biphasic might know more.

**Comment by biphasic** [comment]
hello, sorry I'm still breaking stuff. Fixed by https://github.com/neuromorphs/tonic/commit/85b6968ae499c0d5220f1892347c946b64b1d7ff
notebook runs fine now for me, please upgrade to latest tonic version and try again!

**Comment by fzi-neuromorphic** [comment]
I can confirm that the bug is gone with tonic 0.4.4, thanks for the fast fix!
